apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-deployment
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi@sha256:387071e317ab38f66b8b09b64c44cf1279080977ad1a61efb86545e6d142995d
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: config
          mountPath: "/opt/nifi/nifi-current/conf"
          readOnly: true
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: nifi-properties
          items:
          - key: "nifi.properties"
            path: "nifi.properties"