apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-deployment
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:sha256-387071e317ab38f66b8b09b64c44cf1279080977ad1a61efb86545e6d142995d
        ports:
        - containerPort: 80
